apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
spec:
  ports:
    - protocol: "TCP"
      port: 8090
      targetPort: 4200
  type: LoadBalancer
  selector:
    app: frontend
